server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    instance-id: aigou-config-server:1299.com
    prefer-ip-address: true
spring:
  profiles:
   # active: native #读取本地配置
  application:
    name: AIGOU-CONFIG-SERVER
  cloud:
    config:
      server:
       # native:
        #  search-locations: E:/program/aigou-config #本地配置所在的目录
        git:
          uri: https://github.com/suhongxiang/aigou-config.git
          username: suhongxiang
          password: ww748732